### PR TITLE
Introduce network tokens for cross-network nonce-like verifications

### PR DESCRIPTION
**Pull request by shadyvb**
Introduce network tokens, a nonce-like, global-cache-backed feature for cross-network comms.

humanmade/altis-media#159

### CODE REVIEW

**Comment by rmccue** [comment]
Discussed this a bit with Rob; the big advantage of nonces is that they are self-signed tokens, and hence don't require storage. I don't think we should introduce stored tokens and overload the nonce system this way.

Instead, I think we should look at using regular nonces, and work out any cross-site problems as needed. If we can't get nonces working, then using a similar self-signed token system makes most sense, rather than storing the tokens.

**Comment by shadyvb** [comment]
Yeah, I have been thinking the same, but the problem is that to construct the nonce we need shared information between both sites, which doesn't exist beyond what we share in the request itself, and any shared storage like object-cache.

So from `wp_create_nonce`, the gist is basically: `wp_hash( $tick . '|' . $action . '|' . $uid . '|' . $token, 'nonce' )` , which depends on the shared access to:
- WP Nonce tick ✅ - shared network-wide, time-based, predictable
- Salt ✅ - shared network-wide, is a security element
- Action ✅ - consumer code knows what action to check for, predictable
- Current logged in user ID ❌ - no cookie should be assumed, so no access to that unless passed with the request, and even if passed, it'll need a db query to check for the session token
- Session token ❌ - a user can have multiple session tokens, and they're serialized in db, so we can't search by token even if we passed it, unless we pass the user id as well


I can see two different routes to take:
- Use the nonce without user id/token, less secure but not completely insecure because of the salt, less useful as we lose the user session bit, so a nonce would continue to function beyond the user's session termination.
- Pass the user id/token within the request headers, and use that to verify the nonce, will need a db query to verify the user session token. And it's not 100% secure given we pass parts of the data needed to construct the nonce, so not sure if that's increasing the efficiency of the token.

But, I'd like to discuss why using object-cache for this specific use case is discouraged, given they expire after their TTL, and they're supposed to be used on the admin side, so less scalability concerns.

When we say 'similar self-signed token system', would option 1 suffice in this case ? or do we have something else in mind ?

**Comment by rmccue** [comment]
Can we pass the user's cookies along with the request? That would seem the easiest way to work to me.

**Comment by shadyvb** [comment]
I can try that, sounds like it should work. We'll also need to filter the cap check in case the user is not added to the site, but that's already happening.

**Comment by shadyvb** [comment]
Replaced with https://github.com/humanmade/altis-core/pull/259

**Pull request closed without merging**
